const productData = [
  {
    id: 1,
    name: 'Devashish Gaikwad',
    location: 'Jalna',
    image: 'l1.jpg',
    productType: 'landFarming',
    price: 120,
    totalTokens: 302,
    landArea: 2000,
    rating: 4,
  },
  {
    id: 2,
    name: 'Prasad Reddy',
    location: 'Kakinada',
    image: 'l2.jpg',
    productType: 'landFarming',
    price: 169,
    totalTokens: 1230,
    landArea: 2000,
    rating: 5,
  },
  {
    id: 3,
    name: 'Anitha R K',
    location: 'Jogipeth',
    image: 'l3.jpg',
    productType: 'landFarming',
    price: 170,
    totalTokens: 1009,
    landArea: 2000,
    rating: 4,
  },
];
export default productData;
